Repository NiaOrg/NiaPy, pull requests merged in 2019-04, with the labels that each got.

#193 significant commit of flower pollination algorithm
  NiaPy/algorithms/basic/fpa.py
  Pipfile.lock
Labels: WIP

#198 New examples (algorithm info + custom init population function)
  examples/about_algorithm.py
  examples/custom_init_population.py
  examples/run_fa.py
Labels: enhancement

#199 Foa fix
  NiaPy/algorithms/basic/foa.py
  NiaPy/tests/test_foa.py
  examples/run_foa.py
Labels: LGTM, enhancement

#196 Dependencies, code style, etc.
  .appveyor.yml
  .flake8
  .gitignore
  .pylint.ini
  .travis.yml
  Makefile
  NiaPy/__init__.py
  NiaPy/benchmarks/ackley.py
  NiaPy/benchmarks/alpine.py
  NiaPy/benchmarks/benchmark.py
  NiaPy/benchmarks/bentcigar.py
  NiaPy/benchmarks/chungReynolds.py
  NiaPy/benchmarks/cosinemixture.py
  NiaPy/benchmarks/csendes.py
  NiaPy/benchmarks/discus.py
  NiaPy/benchmarks/dixonprice.py
  NiaPy/benchmarks/elliptic.py
  NiaPy/benchmarks/griewank.py
  NiaPy/benchmarks/happyCat.py
  NiaPy/benchmarks/hgbat.py
  NiaPy/benchmarks/infinity.py
  NiaPy/benchmarks/katsuura.py
  NiaPy/benchmarks/levy.py
  NiaPy/benchmarks/michalewichz.py
  NiaPy/benchmarks/perm.py
  NiaPy/benchmarks/pinter.py
  NiaPy/benchmarks/powell.py
  NiaPy/benchmarks/qing.py
  NiaPy/benchmarks/quintic.py
  NiaPy/benchmarks/rastrigin.py
  NiaPy/benchmarks/ridge.py
  NiaPy/benchmarks/rosenbrock.py
  NiaPy/benchmarks/salomon.py
  NiaPy/benchmarks/schaffer.py
  NiaPy/benchmarks/schumerSteiglitz.py
  NiaPy/benchmarks/schwefel.py
  NiaPy/benchmarks/sphere.py
  NiaPy/benchmarks/step.py
  NiaPy/benchmarks/stepint.py
  NiaPy/benchmarks/styblinskiTang.py
  NiaPy/benchmarks/sumSquares.py
  NiaPy/benchmarks/trid.py
  NiaPy/benchmarks/weierstrass.py
  NiaPy/benchmarks/whitley.py
  NiaPy/benchmarks/zakharov.py
  NiaPy/tests/conftest.py
  NiaPy/tests/test_algorithm.py
  NiaPy/tests/test_ba.py
  NiaPy/tests/test_benchmark_functions.py
  Pipfile
  codemeta.json
  gen-codemeta
  scent.py
  setup.py
  tests/__init__.py
  tests/conftest.py
Labels: WIP, enhancement

#207 MBO algorithm implementation.
  .flake8
  NiaPy/__init__.py
  NiaPy/algorithms/basic/__init__.py
  NiaPy/algorithms/basic/mbo.py
  NiaPy/tests/test_mbo.py
  Pipfile
  examples/run_mbo.py
Labels: feature

#208 Merging logging and printing task in StoppingTask
  NiaPy/task/__init__.py
  NiaPy/task/task.py
  NiaPy/tests/test_statistic.py
  NiaPy/tests/test_utility.py
  examples/run.py
  examples/run_all.bat
  examples/run_all.sh
  examples/run_cmaes.py
  examples/run_pso.py
Labels: enhancement
